name: Terraform Infra Pipeline

on:
  push:
    branches:
      - main

jobs:

  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: devops-infra   ##🔥 your inner folder

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1

      # 🔥 IMPORTANT: Backend initialization
      - name: Terraform Init (Backend)
        run: terraform init -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
